Repository hengband/web, pull requests merged in 2021-09, with the labels that each got.

#127 リンク修正
  src/link.adoc
Labels: documentation

#130 Feature/release3.0.0 alpha37
  src/history.adoc
  src/index.adoc
  src/link.adoc
  src/web_update.adoc
Labels: enhancement

#129 [Add] 3.0.0Alpha37リリース情報追加.
  src/history.adoc
  src/index.adoc
  src/web_update.adoc
Labels: enhancement

#134 リンク整理 Alpha38
  src/link.adoc
Labels: documentation, enhancement

#136 [Add] 3.0.0Alpha38更新情報追加．
  src/history.adoc
  src/index.adoc
  src/web_update.adoc
Labels: documentation

#137 Feature/release3.0.0 alpha38
  src/history.adoc
  src/index.adoc
  src/link.adoc
  src/web_update.adoc
Labels: documentation
